version: '2.1'
services:


  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  mongo-seed:
    build: docker/mongo_seed
    container_name: mongo_seed
    links:
      - mongo

  postgres:
    build: docker/postgres
    image: pluralsight/postgres
    restart: always
    container_name: postgres
    ports:
      - "32769:5432"
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "airflow", "-U", "airflow" ]
      timeout: 45s
      interval: 10s
      retries: 10



  airflow:
    build: docker/airflow
    image: pluralsight/airflow
    restart: always
    container_name: airflow
    environment:
      - AIRFLOW__CORE__FERNET_KEY="Z27wHAQxCObGWbIYyp06PlNoNlV7hyLO5zT74itoQww="
    volumes:
      - ./dags:/usr/local/airflow/dags
    ports:
      - 8080:8080
    depends_on:
      - postgres
    healthcheck:
      test: [ "CMD", "nc", "-z", "airflow", "8080" ]
      timeout: 45s
      interval: 10s
      retries: 10


networks:
  default:
    name: airflow-network